var N = null;var sourcesIndex = {};
sourcesIndex["app_metadata_crate"] = {"name":"","files":["lib.rs"]};
sourcesIndex["parity_wasm"] = {"name":"","dirs":[{"name":"builder","files":["code.rs","data.rs","export.rs","global.rs","import.rs","invoke.rs","memory.rs","misc.rs","mod.rs","module.rs","table.rs"]},{"name":"elements","files":["export_entry.rs","func.rs","global_entry.rs","import_entry.rs","index_map.rs","mod.rs","module.rs","name_section.rs","ops.rs","primitives.rs","reloc_section.rs","section.rs","segment.rs","types.rs"]}],"files":["io.rs","lib.rs"]};
sourcesIndex["proc_macro2"] = {"name":"","files":["detection.rs","fallback.rs","lib.rs","marker.rs","parse.rs","wrapper.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ext.rs","format.rs","ident_fragment.rs","lib.rs","runtime.rs","spanned.rs","to_tokens.rs"]};
sourcesIndex["syn"] = {"name":"","dirs":[{"name":"gen","files":["clone.rs","gen_helper.rs"]}],"files":["attr.rs","await.rs","bigint.rs","buffer.rs","custom_keyword.rs","custom_punctuation.rs","data.rs","derive.rs","discouraged.rs","error.rs","export.rs","expr.rs","ext.rs","generics.rs","group.rs","ident.rs","lib.rs","lifetime.rs","lit.rs","lookahead.rs","mac.rs","macros.rs","op.rs","parse.rs","parse_macro_input.rs","parse_quote.rs","path.rs","print.rs","punctuated.rs","sealed.rs","span.rs","spanned.rs","thread.rs","token.rs","ty.rs","verbatim.rs"]};
sourcesIndex["thiserror"] = {"name":"","files":["aserror.rs","display.rs","lib.rs"]};
sourcesIndex["thiserror_impl"] = {"name":"","files":["ast.rs","attr.rs","expand.rs","fmt.rs","generics.rs","lib.rs","prop.rs","valid.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
